### ISSUE TITLE
사이드 바 이슈 

### ISSUE THREAD

**Issue by yongbeomkwak** [RaniPaper/RaniPaper#12]
@JiDongseok11  사이드바 오류 있습니다 한번 확인해주세요

https://user-images.githubusercontent.com/48616183/204811672-a4325b31-ab99-448d-9230-fc4f6aa3593a.mp4

모든 탭에서 오른쪽 아래 쪽 터치며하면 강제로 기록쪽으로 이동됩니다.

**Comment by JiDongseok11** [comment]
UI 적용시키고 수정해보겠습니다
